name: Publish QGIS Plugin

on:
  release:
    types: [published]

jobs:
  publish:
    name: Package and publish plugin
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install qgis-plugin-ci

      - name: Determine release version
        id: version
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          CLEAN_VERSION="${TAG_NAME#v}"
          echo "version=${CLEAN_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Package plugin
        run: qgis-plugin-ci package "${{ steps.version.outputs.version }}" --allow-uncommitted-changes

      - name: Publish to QGIS Plugin Repository
        env:
          OSGEO_USERNAME: ${{ secrets.QGIS_PLUGIN_REPO_USERNAME }}
          OSGEO_PASSWORD: ${{ secrets.QGIS_PLUGIN_REPO_PASSWORD }}
        run: |
          qgis-plugin-ci release "${{ steps.version.outputs.version }}" \
            --osgeo-username "$OSGEO_USERNAME" \
            --osgeo-password "$OSGEO_PASSWORD" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --allow-uncommitted-changes

      - name: Upload packaged plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: qgis-plugin
          path: class_labeler.${{ steps.version.outputs.version }}.zip
